/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_halifox_airplay_AirplayJni */

#ifndef _Included_com_halifox_airplay_AirplayJni
#define _Included_com_halifox_airplay_AirplayJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_halifox_airplay_AirplayJni
 * Method:    init
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_halifox_airplay_AirplayJni_init
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_halifox_airplay_AirplayJni
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_halifox_airplay_AirplayJni_start
  (JNIEnv *, jobject);

/*
 * Class:     com_halifox_airplay_AirplayJni
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_halifox_airplay_AirplayJni_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_halifox_airplay_AirplayJni
 * Method:    unInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_halifox_airplay_AirplayJni_unInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
